"""
Interactive first-run credential setup. Writes a .env file.
Run: python setup_credentials.py
"""

from pathlib import Path

ENV_FILE = Path(__file__).parent / ".env"

def ask(prompt: str, secret: bool = False) -> str:
    import getpass
    fn = getpass.getpass if secret else input
    return fn(prompt).strip()

def main() -> None:
    print("\n=== Kaggle → S3 Credential Setup ===\n")

    print("-- Kaggle API credentials --")
    print("  Get them from: https://www.kaggle.com/settings > API > Create New Token\n")
    kg_user = ask("Kaggle username: ")
    kg_key  = ask("Kaggle API key (hidden): ", secret=True)

    print("\n-- AWS credentials --")
    print("  Get them from: AWS Console > IAM > Users > Security credentials\n")
    aws_id  = ask("AWS Access Key ID: ")
    aws_sec = ask("AWS Secret Access Key (hidden): ", secret=True)

    lines = [
        "# Auto-generated by setup_credentials.py\n",
        f"KAGGLE_USERNAME={kg_user}\n",
        f"KAGGLE_KEY={kg_key}\n",
        "\n",
        f"AWS_ACCESS_KEY_ID={aws_id}\n",
        f"AWS_SECRET_ACCESS_KEY={aws_sec}\n",
        "AWS_DEFAULT_REGION=us-east-1\n",
        "\n",
        "S3_BUCKET_NAME=assancase-documents-adminpenta\n",
        "S3_PREFIX=supreme-court-pakistan/\n",
    ]

    ENV_FILE.write_text("".join(lines), encoding="utf-8")
    print(f"\n.env written to {ENV_FILE}")
    print("You can now run: python kaggle_to_s3.py")

if __name__ == "__main__":
    main()
